### ISSUE TITLE
So, The "SubMod" Keeps telling me to reinstall it, Then it said there was A error. 

### ISSUE THREAD

**Issue by JustADerpyPlayer** [tw4449/tw4449-Location-Selector-Main-Repository#1]
The "SubMod" keeps telling me to re-install It so I did and it kept telling me to do, So I did It after all the that the game was still the same title "Monika After Story"  
![Capture](https://user-images.githubusercontent.com/71165895/92988549-42638b80-f481-11ea-95b1-75504122cae2.PNG)
So I went to the setting Then went to the SubMod, Then I pressed Update all SubMods.
![Capture 2](https://user-images.githubusercontent.com/71165895/92988565-7dfe5580-f481-11ea-848d-4cb2ad43db47.PNG)
Then it said this, So i cheeked the Log File, And it said this , 
![Capture 3](https://user-images.githubusercontent.com/71165895/92988580-979f9d00-f481-11ea-8526-5cad9d61ccda.PNG)

Fri Sep 11 22:21:56 2020
Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
 

Bootstrap to the start of init.init took 0.09s
Early init took 0.04s
Loader init took 0.13s
Loading error handling took 0.05s
Loading script took 1.75s
Loading persistent took 0.12s
Importing _renpysteam: ImportError('No module named _renpysteam',)
Running init code took 2.96s
Loading analysis data took 0.20s
Analyze and compile ATL took 0.07s
Index archives took 0.00s
Dump and make backups. took 0.00s
Cleaning cache took 0.00s
Making clean stores took 0.00s
DPI scale factor: 1.000000
Creating interface object took 0.10s
Cleaning stores took 0.00s
Init translation took 0.13s
Build styles took 0.01s
Load screen analysis took 0.14s
Analyze screens took 0.00s
Save screen analysis took 0.00s
Prepare screens took 0.11s
Save pyanalysis. took 0.00s
Save bytecode. took 0.00s
Running _start took 0.00s
Performance test:
Interface start took 0.04s

primary display bounds: (0, 0, 1366, 768)
Windowed mode.
Screen sizes: virtual=(1280, 720) physical=(1184, 666) drawable=(1184, 666)
Vendor: 'Intel'
Renderer: 'Intel(R) HD Graphics 520'
Version: '4.5.0 - Build 23.20.16.4973'
Display Info: <Info({'blit_sw_CC': False, 'refresh_rate': 60, 'bitsize': 32, 'wm': True, 'losses': (0, 0, 0, 8), 'hw': False, 'masks': (16711680L, 65280L, 255L, 0L), 'current_h': 768, 'current_w': 1366, 'shifts': (16, 8, 0, 0), 'blit_sw_A': False, 'blit_hw': False, 'blit_sw': False, 'bytesize': 4, 'blit_hw_CC': False, 'blit_hw_A': False, 'video_mem': 268435456})>
Fixed-function is blacklisted.
Extensions:
    GL_3DFX_texture_compression_FXT1
    GL_AMD_depth_clamp_separate
    GL_AMD_vertex_shader_layer
    GL_AMD_vertex_shader_viewport_index
    GL_ARB_ES2_compatibility
    GL_ARB_ES3_1_compatibility
    GL_ARB_ES3_compatibility
    GL_ARB_arrays_of_arrays
    GL_ARB_base_instance
    GL_ARB_blend_func_extended
    GL_ARB_buffer_storage
    GL_ARB_cl_event
    GL_ARB_clear_buffer_object
    GL_ARB_clear_texture
    GL_ARB_clip_control
    GL_ARB_color_buffer_float
    GL_ARB_compatibility
    GL_ARB_compressed_texture_pixel_storage
    GL_ARB_compute_shader
    GL_ARB_conditional_render_inverted
    GL_ARB_conservative_depth
    GL_ARB_copy_buffer
    GL_ARB_copy_image
    GL_ARB_cull_distance
    GL_ARB_debug_output
    GL_ARB_depth_buffer_float
    GL_ARB_depth_clamp
    GL_ARB_depth_texture
    GL_ARB_derivative_control
    GL_ARB_direct_state_access
    GL_ARB_draw_buffers
    GL_ARB_draw_buffers_blend
    GL_ARB_draw_elements_base_vertex
    GL_ARB_draw_indirect
    GL_ARB_draw_instanced
    GL_ARB_enhanced_layouts
    GL_ARB_explicit_attrib_location
    GL_ARB_explicit_uniform_location
    GL_ARB_fragment_coord_conventions
    GL_ARB_fragment_layer_viewport
    GL_ARB_fragment_program
    GL_ARB_fragment_program_shadow
    GL_ARB_fragment_shader
    GL_ARB_fragment_shader_interlock
    GL_ARB_framebuffer_no_attachments
    GL_ARB_framebuffer_object
    GL_ARB_framebuffer_sRGB
    GL_ARB_geometry_shader4
    GL_ARB_get_program_binary
    GL_ARB_get_texture_sub_image
    GL_ARB_gpu_shader5
    GL_ARB_gpu_shader_fp64
    GL_ARB_half_float_pixel
    GL_ARB_half_float_vertex
    GL_ARB_indirect_parameters
    GL_ARB_instanced_arrays
    GL_ARB_internalformat_query
    GL_ARB_internalformat_query2
    GL_ARB_invalidate_subdata
    GL_ARB_map_buffer_alignment
    GL_ARB_map_buffer_range
    GL_ARB_multi_bind
    GL_ARB_multi_draw_indirect
    GL_ARB_multisample
    GL_ARB_multitexture
    GL_ARB_occlusion_query
    GL_ARB_occlusion_query2
    GL_ARB_pixel_buffer_object
    GL_ARB_point_parameters
    GL_ARB_point_sprite
    GL_ARB_polygon_offset_clamp
    GL_ARB_post_depth_coverage
    GL_ARB_program_interface_query
    GL_ARB_provoking_vertex
    GL_ARB_query_buffer_object
    GL_ARB_robust_buffer_access_behavior
    GL_ARB_robustness
    GL_ARB_robustness_isolation
    GL_ARB_sample_shading
    GL_ARB_sampler_objects
    GL_ARB_seamless_cube_map
    GL_ARB_seamless_cubemap_per_texture
    GL_ARB_separate_shader_objects
    GL_ARB_shader_atomic_counter_ops
    GL_ARB_shader_atomic_counters
    GL_ARB_shader_bit_encoding
    GL_ARB_shader_draw_parameters
    GL_ARB_shader_group_vote
    GL_ARB_shader_image_load_store
    GL_ARB_shader_image_size
    GL_ARB_shader_objects
    GL_ARB_shader_precision
    GL_ARB_shader_stencil_export
    GL_ARB_shader_storage_buffer_object
    GL_ARB_shader_subroutine
    GL_ARB_shader_texture_image_samples
    GL_ARB_shading_language_100
    GL_ARB_shading_language_420pack
    GL_ARB_shading_language_packing
    GL_ARB_shadow
    GL_ARB_stencil_texturing
    GL_ARB_sync
    GL_ARB_tessellation_shader
    GL_ARB_texture_barrier
    GL_ARB_texture_border_clamp
    GL_ARB_texture_buffer_object
    GL_ARB_texture_buffer_object_rgb32
    GL_ARB_texture_buffer_range
    GL_ARB_texture_compression
    GL_ARB_texture_compression_bptc
    GL_ARB_texture_compression_rgtc
    GL_ARB_texture_cube_map
    GL_ARB_texture_cube_map_array
    GL_ARB_texture_env_add
    GL_ARB_texture_env_combine
    GL_ARB_texture_env_crossbar
    GL_ARB_texture_env_dot3
    GL_ARB_texture_float
    GL_ARB_texture_gather
    GL_ARB_texture_mirror_clamp_to_edge
    GL_ARB_texture_mirrored_repeat
    GL_ARB_texture_multisample
    GL_ARB_texture_non_power_of_two
    GL_ARB_texture_query_levels
    GL_ARB_texture_query_lod
    GL_ARB_texture_rectangle
    GL_ARB_texture_rg
    GL_ARB_texture_rgb10_a2ui
    GL_ARB_texture_stencil8
    GL_ARB_texture_storage
    GL_ARB_texture_storage_multisample
    GL_ARB_texture_swizzle
    GL_ARB_texture_view
    GL_ARB_timer_query
    GL_ARB_transform_feedback2
    GL_ARB_transform_feedback3
    GL_ARB_transform_feedback_instanced
    GL_ARB_transpose_matrix
    GL_ARB_uniform_buffer_object
    GL_ARB_vertex_array_bgra
    GL_ARB_vertex_array_object
    GL_ARB_vertex_attrib_64bit
    GL_ARB_vertex_attrib_binding
    GL_ARB_vertex_buffer_object
    GL_ARB_vertex_program
    GL_ARB_vertex_shader
    GL_ARB_vertex_type_10f_11f_11f_rev
    GL_ARB_vertex_type_2_10_10_10_rev
    GL_ARB_viewport_array
    GL_ARB_window_pos
    GL_ATI_separate_stencil
    GL_EXT_abgr
    GL_EXT_bgra
    GL_EXT_blend_color
    GL_EXT_blend_equation_separate
    GL_EXT_blend_func_separate
    GL_EXT_blend_minmax
    GL_EXT_blend_subtract
    GL_EXT_clip_volume_hint
    GL_EXT_compiled_vertex_array
    GL_EXT_direct_state_access
    GL_EXT_draw_buffers2
    GL_EXT_draw_range_elements
    GL_EXT_fog_coord
    GL_EXT_framebuffer_blit
    GL_EXT_framebuffer_multisample
    GL_EXT_framebuffer_object
    GL_EXT_geometry_shader4
    GL_EXT_gpu_program_parameters
    GL_EXT_gpu_shader4
    GL_EXT_multi_draw_arrays
    GL_EXT_packed_depth_stencil
    GL_EXT_packed_float
    GL_EXT_packed_pixels
    GL_EXT_polygon_offset_clamp
    GL_EXT_rescale_normal
    GL_EXT_secondary_color
    GL_EXT_separate_specular_color
    GL_EXT_shader_framebuffer_fetch
    GL_EXT_shader_integer_mix
    GL_EXT_shadow_funcs
    GL_EXT_stencil_two_side
    GL_EXT_stencil_wrap
    GL_EXT_texture3D
    GL_EXT_texture_array
    GL_EXT_texture_compression_s3tc
    GL_EXT_texture_edge_clamp
    GL_EXT_texture_env_add
    GL_EXT_texture_env_combine
    GL_EXT_texture_filter_anisotropic
    GL_EXT_texture_integer
    GL_EXT_texture_lod_bias
    GL_EXT_texture_rectangle
    GL_EXT_texture_sRGB
    GL_EXT_texture_sRGB_decode
    GL_EXT_texture_shared_exponent
    GL_EXT_texture_snorm
    GL_EXT_texture_storage
    GL_EXT_texture_swizzle
    GL_EXT_timer_query
    GL_EXT_transform_feedback
    GL_IBM_texture_mirrored_repeat
    GL_INTEL_conservative_rasterization
    GL_INTEL_fragment_shader_ordering
    GL_INTEL_framebuffer_CMAA
    GL_INTEL_map_texture
    GL_INTEL_multi_rate_fragment_shader
    GL_INTEL_performance_query
    GL_KHR_blend_equation_advanced
    GL_KHR_blend_equation_advanced_coherent
    GL_KHR_context_flush_control
    GL_KHR_debug
    GL_KHR_texture_compression_astc_ldr
    GL_NV_blend_square
    GL_NV_conditional_render
    GL_NV_primitive_restart
    GL_NV_texgen_reflection
    GL_SGIS_generate_mipmap
    GL_SGIS_texture_edge_clamp
    GL_SGIS_texture_lod
    GL_SUN_multi_draw_arrays
    GL_WIN_swap_hint
    WGL_EXT_swap_control
Number of texture units: 8
Using shader environment.
Using copy RTT.
Using gl renderer.
Texture testing:
- Hardware max texture size: 16384
- 64px textures work.
- 128px textures work.
- 256px textures work.
- 512px textures work.
- 1024px textures work.
- 2048px textures work.
Total time until interface ready: 6.57899999619s
- Target is 5 frames in 0.333333333333 seconds.
- Frame drawn at 0.000000 seconds.
- Frame drawn at 0.021000 seconds.
- Frame drawn at 0.037000 seconds.
- Frame drawn at 0.053000 seconds.
- Frame drawn at 0.069000 seconds.
- 0.069000 seconds to render 5 frames.
The window was minimized.
The window was restored.

primary display bounds: (0, 0, 1366, 768)
Windowed mode.
Screen sizes: virtual=(1280, 720) physical=(1184, 666) drawable=(1184, 666)
The window was minimized.
The window was restored.

primary display bounds: (0, 0, 1366, 768)
Windowed mode.
Screen sizes: virtual=(1280, 720) physical=(1184, 666) drawable=(1184, 666)
The window was minimized.
The window was restored.

primary display bounds: (0, 0, 1366, 768)
Windowed mode.
Screen sizes: virtual=(1280, 720) physical=(1184, 666) drawable=(1184, 666)
The window was minimized.
The window was restored.

primary display bounds: (0, 0, 1366, 768)
Windowed mode.
Screen sizes: virtual=(1280, 720) physical=(1184, 666) drawable=(1184, 666)
The window was minimized.
The window was restored.

primary display bounds: (0, 0, 1366, 768)
Windowed mode.
Screen sizes: virtual=(1280, 720) physical=(1184, 666) drawable=(1184, 666)
The window was minimized.
The window was restored.

primary display bounds: (0, 0, 1366, 768)
Windowed mode.
Screen sizes: virtual=(1280, 720) physical=(1184, 666) drawable=(1184, 666)
The window was minimized.
T

**Comment by Cdino11** [comment]
have you re opened the game since? i notices some the the tags were wrong, causing the updater to think it needed an update. it should work now

**Comment by JustADerpyPlayer** [comment]
> have you re opened the game since? i noticed some the the tags were wrong, causing the updater to think it needed an update. it should work now

Yes I opened the game, I did not open It for a week last week I started Interacting with Monika today.

**Comment by Cdino11** [comment]
so has it stopped telling you to update the submods?

**Comment by JustADerpyPlayer** [comment]
> so has it stopped telling you to update the submods?

Yes, I tried updating it a Couple of times and it just game me a error at the last time.

**Comment by Cdino11** [comment]
that's good, also you'll know if there is a true update if you look at the update details.

**Comment by tw4449** [comment]
Cdino, I don't think you read closely. They said they still got an error.

**Comment by Cdino11** [comment]
> > so has it stopped telling you to update the submods?
> 
> Yes, I tried updating it a Couple of times and it just game me a error at the last time.

try installing the all in one now, it should no longer give you update notices and has the latest version of the plugin where you can disable the notifications if it does persists. that being said let up know if you still have update notifications as there may be another problem

**Comment by Booplicate** [comment]
Hey there. The errors are logged in `/log/mas_log.txt`. Next time you see an error like that, open that log and scroll down. There should be a clear description why it happened.

Also if you open the tab with update descriptions, you'll see what version you're currently using and what version is available in the update.
